

#plak hier de haiku functions onder elkaar
print("Haiku: ", "by Robert en David")
print(" ik ben aan het poepen")
print("ik was te veel aan het snoepen")
print("wat ben je een snoeperd")
print("ik was bezig met je moeder")
print("poep met poeder")
print("geen geloeder")
print("mijn naam is robby dude geen duder")
print("ik scoor wel alleen niet me doelen")
print("wat zijn jullie oenen")
print("ik heb fire schoenen")
print("toen kwam ik je roepen")
print("dat was poep geen snoep")
print("gefeliciteerd nu is me hele familie getraumatiseerd en bedroefd")
print("dat heb ik je beproefd")
print("niks zeggen ik weet dat je me poep loeved")
print("zit er mais in dan is dat niet zo goed")
print("met deze rap komen we nooit uit de hood")
print("ik weet je vind t niet zo lekker toch weet ik dat het niet hoeft")
print("ik zeg toch dat het niet hoeft dat betekent dat je het niet moet")
print("ik zit in de auto ik toet toet")
print("ik weet dat je me d moet")
print("maar je weet dat ik je niet hoef dus ben ik niet in de mood")
print("zo bruin net marvel ik lijk op fking groot")
print("je bent niet gezond eet is wat fruit")
print("chickie heeft zoveel haar lijkt net een dude")
print("niet beledigd zijn het was niet eens rude")
print("niet huilen want zo heb ik het niet bedoeld")
print("ik probeer je niet te kwetsen dat is niet me doel")
print("man waar is je gevoel")
print("blijf zo praten dan sla ik je op je smoel")
print("twee guns op me ze noemen me deadpool")
print("ik ga je poep laten vliegen geen redbull")
print("dat is je favo smaak met je kut juul")
print("praat niet met me nu klink ik als een fool")
print("je heb niet zulke poep dan ben je ook minder cool")
print("je bent op voetbal echt geen liverpool")
print("ik heb geen shank maar ik steek je met me tool")
print("kom dichterbij dan laat ik je zien wat ik bedoel")
print("je kwijlt op me net een pitbull")
print("lijkt wel op een drool")
print("vieze daggoe wil zitten op me stoel")




#laat de code hieronder met rust
Haiku1()
Haiku2()
Haiku3()
